sudo: required
language: node_js
node_js:
  - "stable"
services: mongodb
before_script:
  - mongo test --eval 'db.users.insertOne({name:"Magesh",user_id:1,email_id:"mageshchandru35@gmail.com"});'
script:
  - echo "hello"
